import streamlit as st
import pandas as pd
import plotly.express as px
from datetime import datetime


def generate_insights(df):
    insights = []

    insights.append(
        f"Dataset contains {len(df)} rows and {len(df.columns)} columns."
    )

    insights.append(
        f"Missing values detected: {df.isnull().sum().sum()}."
    )

    duplicate_count = df.duplicated().sum()
    insights.append(
        f"Duplicate rows found: {duplicate_count}."
    )

    categorical_columns = df.select_dtypes(include="object").columns

    if len(categorical_columns) > 0:
        top_column = categorical_columns[0]
        most_common = df[top_column].mode()[0]

        insights.append(
            f"Most common {top_column} is '{most_common}'."
        )

    return insights


def create_profile_report(df, insights):
    report = f"""
AI EXCEL DATA ANALYST - DATASET PROFILE REPORT

Dataset Summary
---------------
Total Rows: {len(df)}
Total Columns: {len(df.columns)}
Missing Values: {df.isnull().sum().sum()}
Duplicate Rows: {df.duplicated().sum()}

Columns
-------
{', '.join(df.columns)}

Quick Insights
--------------
"""

    for item in insights:
        report += f"- {item}\n"

    return report


def answer_data_question(df, question):
    question_lower = question.lower()

    if "missing" in question_lower:
        return f"The dataset has {df.isnull().sum().sum()} missing values."

    if "duplicate" in question_lower:
        return f"The dataset has {df.duplicated().sum()} duplicate rows."

    if "rows" in question_lower:
        return f"The dataset contains {len(df)} rows."

    if "columns" in question_lower:
        return f"The dataset contains {len(df.columns)} columns."

    if "highest" in question_lower or "most" in question_lower or "top" in question_lower or "often" in question_lower:
        for col in df.columns:
            if col.lower() in question_lower:
                top_value = df[col].value_counts().idxmax()
                top_count = df[col].value_counts().max()
                return f"The most common value in {col} is '{top_value}' with {top_count} records."

    return (
        "I can answer questions about rows, columns, missing values, duplicates, "
        "and the most common value in a selected column."
    )

from datetime import datetime

def generate_executive_report(df):

    report = f"""
AI EXCEL DATA ANALYST
EXECUTIVE DATASET PROFILE REPORT

==================================================

Report Date
{datetime.now().strftime("%Y-%m-%d %H:%M")}

==================================================
DATASET OVERVIEW
==================================================

Total Records      : {len(df)}
Total Columns      : {len(df.columns)}
Missing Values     : {df.isnull().sum().sum()}
Duplicate Rows     : {df.duplicated().sum()}

==================================================
AVAILABLE COLUMNS
==================================================

"""

    for column in df.columns:
        report += f"• {column}\n"

    report += "\n"
    report += "==================================================\n"
    report += "TOP FINDINGS\n"
    report += "==================================================\n\n"

    for col in df.select_dtypes(include="object").columns:

        top_value = df[col].value_counts().idxmax()

        top_count = df[col].value_counts().max()

        report += (
            f"Most common {col}: "
            f"{top_value} ({top_count} records)\n"
        )

    report += "\n" 
    
    report += "==================================================\n"
    report += "QUICK INSIGHTS\n"
    report += "==================================================\n\n"

    
    insights = generate_insights(df)

    for item in insights:
        report += f"• {item}\n"

    report += "\n"
    report += "==================================================\n"
    report += "RECOMMENDATIONS\n"
    report += "==================================================\n\n"

    report += "• Review missing values before analysis.\n"
    report += "• Remove duplicate records if necessary.\n"
    report += "• Explore trends using interactive charts.\n"
    report += "• Investigate the most frequent categories.\n"
    report += "• Export visualizations for management reporting.\n"

    report += "\n"
    report += "==================================================\n"
    report += "Generated by AI Excel Data Analyst\n"

    return report


st.set_page_config(
    page_title="AI Excel Data Analyst",
    page_icon="📊",
    layout="wide"
)

st.markdown(
    """
    <style>
    .main {
        background-color: #f8fafc;
    }

    h1, h2, h3 {
        color: #1f2937;
    }

    .stMetric {
        background-color: #ffffff;
        padding: 16px;
        border-radius: 14px;
        border: 1px solid #e5e7eb;
        box-shadow: 0 1px 4px rgba(0,0,0,0.06);
    }

    .stButton > button {
        border-radius: 10px;
        font-weight: 600;
    }

    .stDownloadButton > button {
        border-radius: 10px;
        background-color: #0f766e;
        color: white;
        font-weight: 600;
        border: none;
    }
    </style>
    """,
    unsafe_allow_html=True
)


if "qa_history" not in st.session_state:
    st.session_state.qa_history = []

st.title("📊 AI Excel Data Analyst & Reporting Assistant")

st.markdown(
    """
Upload CSV or Excel files, review dataset quality, explore interactive charts, 
ask plain-English questions, and download executive-ready reports.
"""
)

uploaded_file = st.file_uploader(
    "Upload your CSV or Excel file",
    type=["csv", "xlsx"]
)

if uploaded_file is not None:

    if uploaded_file.name.endswith(".csv"):
        df = pd.read_csv(uploaded_file)
    else:
        df = pd.read_excel(uploaded_file)

    st.divider()
    st.subheader("Dataset Preview")
    st.dataframe(df)

    csv = df.to_csv(index=False).encode("utf-8")

    st.download_button(
        label="⬇️ Download Dataset as CSV",
        data=csv,
        file_name="filtered_dataset.csv",
        mime="text/csv"
)

    st.divider()
    st.subheader("Summary Cards")

    col1, col2, col3, col4 = st.columns(4)

    with col1:
        st.metric("Total Rows", len(df))

    with col2:
        st.metric("Columns", len(df.columns))

    with col3:
        st.metric("Missing Values", df.isnull().sum().sum())

    with col4:
        st.metric("Duplicate Rows", df.duplicated().sum())


    st.divider()
    st.subheader("Dataset Health Check")

    health_df = pd.DataFrame({
        "Column": df.columns,
        "Missing Values": df.isnull().sum().values,
        "Data Type": df.dtypes.astype(str).values
    })

    st.dataframe(health_df)

    

    st.divider()

    insights = generate_insights(df)

    st.subheader("📊 Quick Insights")
    with st.expander("View Quick Insights", expanded=True):
        for item in insights:
            st.write("•", item)

    st.divider()
    st.subheader("📄 Executive Dataset Report")

    executive_report = generate_executive_report(df)

    st.download_button(
        "📄 Download Executive Report",
        executive_report,
        file_name="Executive_Report.txt",
        mime="text/plain"
    )

    with st.expander("View Executive Report"):
        st.text(executive_report)

    st.divider()
    st.subheader("📈 Interactive Chart")

    chart_column = st.selectbox(
        "Select a column to visualize",
        df.columns
    )

    chart_data = (
        df[chart_column]
        .value_counts()
        .reset_index()
    )

    chart_data.columns = [chart_column, "Count"]

    fig = px.bar(
        chart_data,
        x=chart_column,
        y="Count",
        title=f"{chart_column} Distribution"
    )

    st.plotly_chart(fig, use_container_width=True)

    st.divider()
    st.subheader("Ask a Question About the Dataset")

    user_question = st.text_input(
        "Ask a question, for example: Which month appears most often?"
    )

    if st.button("Ask Data Analyst"):
        answer = answer_data_question(df, user_question)

        st.session_state.qa_history.append({
            "question": user_question,
            "answer": answer
        })

        st.markdown("### Answer")
        st.write(answer)

        st.download_button(
            label="Download Answer",
            data=answer,
            file_name="data_answer.txt",
            mime="text/plain"
        )

    if st.session_state.qa_history:
        st.subheader("Q&A History")

        for index, item in enumerate(reversed(st.session_state.qa_history), start=1):
            with st.expander(f"Question {index}: {item['question']}"):
                st.write(item["answer"])

        if st.button("Reset Q&A History"):
            st.session_state.qa_history = []
            st.success("Q&A history cleared.")